# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    providers:
        in_memory:
             memory:
                users:
                    %backend_user%:  { password: %backend_pass%, roles: 'ROLE_ADMIN' }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
